// <auto-generated />
using System;
using DesiCorner.Services.CartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesiCorner.Services.CartAPI.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20251218204301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesiCorner.Services.CartAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "WELCOME10",
                            CreatedAt = new DateTime(2025, 12, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8381),
                            CreatedBy = "System",
                            Description = "Welcome discount for new customers",
                            DiscountAmount = 10m,
                            DiscountType = "Fixed",
                            ExpiryDate = new DateTime(2026, 12, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8369),
                            IsActive = true,
                            MaxUsageCount = 1000,
                            MinAmount = 0m,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "SAVE20",
                            CreatedAt = new DateTime(2025, 12, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8387),
                            CreatedBy = "System",
                            Description = "Save $20 on orders over $100",
                            DiscountAmount = 20m,
                            DiscountType = "Fixed",
                            ExpiryDate = new DateTime(2026, 6, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8386),
                            IsActive = true,
                            MaxUsageCount = 500,
                            MinAmount = 100m,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "PERCENT15",
                            CreatedAt = new DateTime(2025, 12, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8396),
                            CreatedBy = "System",
                            Description = "15% off your order (max $50)",
                            DiscountAmount = 15m,
                            DiscountType = "Percentage",
                            ExpiryDate = new DateTime(2026, 3, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8395),
                            IsActive = true,
                            MaxDiscount = 50m,
                            MaxUsageCount = 1000,
                            MinAmount = 50m,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "FEAST50",
                            CreatedAt = new DateTime(2025, 12, 18, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8411),
                            CreatedBy = "System",
                            Description = "Big feast discount - $50 off orders over $200",
                            DiscountAmount = 50m,
                            DiscountType = "Fixed",
                            ExpiryDate = new DateTime(2026, 1, 17, 20, 43, 1, 657, DateTimeKind.Utc).AddTicks(8400),
                            IsActive = true,
                            MaxUsageCount = 100,
                            MinAmount = 200m,
                            UsedCount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
