// <auto-generated />
using System;
using DesiCorner.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesiCorner.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251104202706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8712),
                            Description = "Start your meal with these delicious appetizers",
                            DisplayOrder = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8714),
                            Description = "Hearty main dishes to satisfy your hunger",
                            DisplayOrder = 2,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8715),
                            Description = "Aromatic rice dishes with your choice of protein",
                            DisplayOrder = 3,
                            Name = "Biryani"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8718),
                            Description = "Sweet endings to your perfect meal",
                            DisplayOrder = 4,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8721),
                            Description = "Refreshing drinks to complement your meal",
                            DisplayOrder = 5,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergens")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpiceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dcd0793-899e-40c1-aa73-67e2be8ed904"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8827),
                            Description = "Crispy pastry filled with spiced potatoes and peas",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Samosa (2 pcs)",
                            PreparationTime = 10,
                            Price = 4.99m,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("fa0bfe8a-423d-4ef9-9f9f-7f8e9ada2747"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8865),
                            Description = "Tender chicken marinated in yogurt and spices, grilled to perfection",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Chicken Tikka",
                            PreparationTime = 15,
                            Price = 12.99m,
                            SpiceLevel = 3
                        },
                        new
                        {
                            Id = new Guid("f85c305d-4780-443d-9ab6-339d72227470"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8868),
                            Description = "Cottage cheese cubes in rich tomato and cream sauce",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Paneer Tikka Masala",
                            PreparationTime = 20,
                            Price = 13.99m,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("48841368-3764-427e-966f-bbc54c091b70"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8870),
                            Description = "Tender chicken in creamy tomato sauce with butter and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Butter Chicken",
                            PreparationTime = 25,
                            Price = 15.99m,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("2115f9b3-ff26-4a30-af88-052e7d3f5f07"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8872),
                            Description = "Fragrant basmati rice cooked with chicken, herbs and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Chicken Biryani",
                            PreparationTime = 30,
                            Price = 16.99m,
                            SpiceLevel = 3
                        },
                        new
                        {
                            Id = new Guid("78f46fc3-c2b2-44a3-810c-20bc2da9eb84"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8874),
                            Description = "Aromatic basmati rice with mixed vegetables and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Vegetable Biryani",
                            PreparationTime = 25,
                            Price = 13.99m,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("6569f699-da0e-4008-8436-150dbcc70641"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8884),
                            Description = "Soft milk dumplings soaked in rose-flavored sugar syrup",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Gulab Jamun (3 pcs)",
                            PreparationTime = 5,
                            Price = 5.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = new Guid("b97ba28c-15fa-4e89-a93b-8289254af2a6"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8886),
                            Description = "Refreshing yogurt drink blended with sweet mangoes",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Mango Lassi",
                            PreparationTime = 5,
                            Price = 4.99m,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = new Guid("d3f7c900-ab73-438e-9e2c-7020dd0e0d8c"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 11, 4, 20, 27, 4, 364, DateTimeKind.Utc).AddTicks(8890),
                            Description = "Traditional Indian tea brewed with aromatic spices",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Masala Chai",
                            PreparationTime = 5,
                            Price = 2.99m,
                            SpiceLevel = 0
                        });
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Product", b =>
                {
                    b.HasOne("DesiCorner.Services.ProductAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
