// <auto-generated />
using System;
using DesiCorner.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesiCorner.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251216211647_AddReviewsAndRatings")]
    partial class AddReviewsAndRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2523),
                            Description = "Start your meal with these delicious appetizers",
                            DisplayOrder = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2526),
                            Description = "Hearty main dishes to satisfy your hunger",
                            DisplayOrder = 2,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2528),
                            Description = "Aromatic rice dishes with your choice of protein",
                            DisplayOrder = 3,
                            Name = "Biryani"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2531),
                            Description = "Sweet endings to your perfect meal",
                            DisplayOrder = 4,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2532),
                            Description = "Refreshing drinks to complement your meal",
                            DisplayOrder = 5,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Allergens")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("SpiceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e00f505-c687-4470-a6d0-a8856d01d3d1"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2647),
                            Description = "Crispy pastry filled with spiced potatoes and peas",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Samosa (2 pcs)",
                            PreparationTime = 10,
                            Price = 4.99m,
                            ReviewCount = 0,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("43fada9a-9583-457f-93df-5d7fcb175bf0"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2731),
                            Description = "Tender chicken marinated in yogurt and spices, grilled to perfection",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Chicken Tikka",
                            PreparationTime = 15,
                            Price = 12.99m,
                            ReviewCount = 0,
                            SpiceLevel = 3
                        },
                        new
                        {
                            Id = new Guid("bb7e26fd-a14c-4153-9299-fa6d77236c1d"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2734),
                            Description = "Cottage cheese cubes in rich tomato and cream sauce",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Paneer Tikka Masala",
                            PreparationTime = 20,
                            Price = 13.99m,
                            ReviewCount = 0,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("94cd611f-1b0f-4cf6-b50d-a16fc9d8306e"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2743),
                            Description = "Tender chicken in creamy tomato sauce with butter and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Butter Chicken",
                            PreparationTime = 25,
                            Price = 15.99m,
                            ReviewCount = 0,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("cdabf734-23b1-408e-9d2e-4ef875413e82"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2746),
                            Description = "Fragrant basmati rice cooked with chicken, herbs and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = false,
                            IsVegetarian = false,
                            Name = "Chicken Biryani",
                            PreparationTime = 30,
                            Price = 16.99m,
                            ReviewCount = 0,
                            SpiceLevel = 3
                        },
                        new
                        {
                            Id = new Guid("9318d852-74ca-4048-b0b0-c979d43a6c19"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2748),
                            Description = "Aromatic basmati rice with mixed vegetables and spices",
                            IsAvailable = true,
                            IsSpicy = true,
                            IsVegan = true,
                            IsVegetarian = true,
                            Name = "Vegetable Biryani",
                            PreparationTime = 25,
                            Price = 13.99m,
                            ReviewCount = 0,
                            SpiceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("65e5a6e7-a5f5-4521-9a70-ea786e874dfc"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2751),
                            Description = "Soft milk dumplings soaked in rose-flavored sugar syrup",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Gulab Jamun (3 pcs)",
                            PreparationTime = 5,
                            Price = 5.99m,
                            ReviewCount = 0,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = new Guid("5288829d-e04c-454f-a6aa-cc9ed067183c"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2757),
                            Description = "Refreshing yogurt drink blended with sweet mangoes",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Mango Lassi",
                            PreparationTime = 5,
                            Price = 4.99m,
                            ReviewCount = 0,
                            SpiceLevel = 0
                        },
                        new
                        {
                            Id = new Guid("9db5a77c-f4f1-4cbf-828f-025a68ca41e5"),
                            AverageRating = 0.0,
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 16, 21, 16, 44, 733, DateTimeKind.Utc).AddTicks(2762),
                            Description = "Traditional Indian tea brewed with aromatic spices",
                            IsAvailable = true,
                            IsSpicy = false,
                            IsVegan = false,
                            IsVegetarian = true,
                            Name = "Masala Chai",
                            PreparationTime = 5,
                            Price = 2.99m,
                            ReviewCount = 0,
                            SpiceLevel = 0
                        });
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int>("NotHelpfulCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProductId", "UserId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Product", b =>
                {
                    b.HasOne("DesiCorner.Services.ProductAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Review", b =>
                {
                    b.HasOne("DesiCorner.Services.ProductAPI.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DesiCorner.Services.ProductAPI.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
